export default new Set([
  // Words reserved by Vento, used internally. In general, don't use variable
  // names starting with two underscores to be future-proof and avoid clashes.
  "__file",
  "__env",
  "__defaults",
  "__err",
  "__exports",
  "__pos",
  // JS reserved words, and some "dangerous" words like `let`, `async` or
  // `undefined`, which aren't technically reserved but don't name your
  // variables that.
  "async",
  "await",
  "break",
  "case",
  "catch",
  "class",
  "const",
  "continue",
  "debugger",
  "default",
  "delete",
  "do",
  "else",
  "enum",
  "export",
  "extends",
  "false",
  "finally",
  "for",
  "function",
  "if",
  "import",
  "in",
  "instanceof",
  "let",
  "new",
  "null",
  "return",
  "super",
  "switch",
  "this",
  "throw",
  "true",
  "try",
  "typeof",
  "undefined",
  "var",
  "void",
  "while",
  "with",
  "yield",
]);
